name: site-deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: stashapp/CommunityScrapers
          path: CommunityScrapers
      - uses: actions/setup-node@v4
      - run: |
          npm ci && \
          npm run generate
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4